Added Testing add and remove functions
farouqdaif1/To-Do-list2 pull request #6
Opened 2021-11-11 07:52 UTC by Lockless404

Added testing for the following functions:
add()
remover()
edit()
completeTask()
clearCompleteTask()

2021-11-11 08:38 UTC, mikethreels requested changes
Hi Farouq, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-11 08:38 UTC, mikethreels commented on __tests__/localstorage.test.js
> +  });
- [ ] Good job on wrapping the tests inside the describe 👍 however you are not actually testing the code you've written, but just the mock function you've written inside of your tests.

2021-11-11 08:38 UTC, mikethreels commented on __tests__/localstorage.test.js
> +  });
- [ ] Good job on wrapping the tests inside the describe 👍 however you are not actually testing the code you've written, but just the mock function you've written inside of your tests.

2021-11-11 08:38 UTC, mikethreels commented on __tests__/localstorage.test.js
> +  });
- [ ] Good job on wrapping the tests inside the describe 👍 however you are not actually testing the code you've written, but just the mock function you've written inside of your tests.

2021-11-11 08:38 UTC, mikethreels commented on __tests__/localstorage.test.js
> +  });
- [ ] Good job on wrapping the tests inside the describe 👍 however you are not actually testing the code you've written, but just the mock function you've written inside of your tests.

2021-11-11 08:38 UTC, mikethreels commented on __tests__/localstorage.test.js
> +  });
- [ ] Good job on wrapping the tests inside the describe 👍 however you are not actually testing the code you've written, but just the mock function you've written inside of your tests.

2021-11-11 13:22 UTC, farouqdaif1 commented
Hello CR! :)

Please note that my mock functions for adding, editing, and removing list items are working just fine with local storage, and I used the same logic in those functions! However, I'm just following the [instructions](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/tests_1.md#:~:text=Take%20a%20look%20at%20each%20of%20these%20functions.%20Are%20they%20pure%20functions%3F%20If%20the%20answer%20is%20%22yes%22%20then%20writing%20tests%20for%20them%20should%20be%20straightforward.%20Some%20of%20those%20functions%20however%20will%20update%20localStorage%20and%20manipulate%20the%20DOM.%20For%20those%2C%20you%20will%20need%20to%20use%20mocks%3A). Please tell me if I'm getting something wrong! 🙏 Thanks!

2021-11-11 15:00 UTC, ArthurGC requested changes
Hi  @Lockless404 

Sorry 😢. You didn't implement any changes from the previous reviewer's suggestion. 

![](https://media0.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif)

## Good Points :+1: :

## Aspects to improve ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-11-11 15:00 UTC, ArthurGC commented on __tests__/localstorage.test.js
> +  });
- [ ] As the previous reviewer said, you should test your code and not a mock because you know what your mock will return so it does not make sense. Try to check [Unit tests in JavaScript](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/testing/lesson_more_about_unit_tests_in_js.md) again.
- The idea is to use fake HTML and call the functions you implemented in your project and check if they work well with that fake HTML.
![Mock HTML](https://user-images.githubusercontent.com/79876959/141319597-23f86e1f-cc36-4301-8101-8c389e66c67d.PNG)
- About LocalStorage, it refers to functions that use the localStorage like:
https://github.com/farouqdaif1/To-Do-list2/blob/2e38c36a75e535c4defb5480a69fa30586a34ae1/src/add-remove.js#L1-L14
If you see the function used a LocalStorage inside and you need to mock it. (It is an example I don't say you need to test that function from the example. It is only for explanation). If your add and remove functions don't use a LocalStorage. You shouldn't mock anything. It is only for functions like the example.

2021-11-12 00:38 UTC, farouqdaif1 commented
Hi CR, I implemented what was required for me from the previous reviews. I'd appreciate if it gets approved because this is my last attempt!
Thank you for your time!

2021-11-12 00:48 UTC, Mihndim2020 approved these changes
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
Hi @farouqdaif1, 

Your project is complete! Great work on making the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

![Congratulations-Memes-FEATURED](https://user-images.githubusercontent.com/65852621/133696300-b506e476-dc1a-443e-935a-c6f434e788b6.jpg)

## Optional suggestions

_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-12 06:43 UTC, merged